spring.config.import=optional:file:.env[.properties]
spring.application.name=devassist

spring.datasource.url=jdbc:postgresql://localhost:5432/devassist
spring.datasource.username=devassist
spring.datasource.password=devassist
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=${GROQ_API_KEY}
groq.model=openai/gpt-oss-120b

github.api.url=https://api.github.com
github.token=${GITHUB_TOKEN}